name: Update File with Latest Gist Commit Hash

on:
  push:
    branches:
      - main  # Change to your main branch name if different

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute Bash script
      run: |
        bash change.sh ${{ secrets.DEVKEY }} ${{ secrets.GISTID }}
